### ISSUE TITLE
delete node on a camel route seems to often get the wrong node ;)

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-forge#317] opened 2016-06-23 07:37 UTC
I tried to delete the `log:foo` in a route like...

```
when ...
  log:foo
  to bar
```

and it deleted the `to` :)

We should check we can delete either of the above nodes and it gets the right one ;)

**Comment by davsclaus** [comment] 2016-06-23 10:44
I could not reproduce this from IDEA with an xml file.

Trying the web ui now. Just reinstalled due the new OS3 release.

**Comment by jstrachan** [comment] 2016-06-23 11:09
it could well be a bug in the web console ;)

**Comment by davsclaus** [comment] 2016-06-23 11:19
I just deleted the transform node and the UI re-painted itself but it was wrong. But the source code is correct:

```
<routes xmlns="http://camel.apache.org/schema/spring">
    <route id="cbr-route">
      <from uri="timer:foo?period=5000"/>
      <!-- generate random number message, using a 3 digit number -->
      <choice>
        <when>
          <simple>${body} &gt; 500</simple>
          <log message="High priority message : ${body}"/>
        </when>
        <otherwise>
          <log message="Low priority message  : ${body}"/>
        </otherwise>
      </choice>
    </route>
</routes>
```

**Comment by davsclaus** [comment] 2016-06-23 11:28
It seems the web console updates the Camel overview wrong. The command `camel-get-routes-xml` seems to return old data, after you delete/add nodes etc.

**Comment by davsclaus** [comment] 2016-06-30 08:01
Got some fixes in, assume it works better. Lets close this. Reopen if something is still a problem.

**Closed as completed by davsclaus** 2016-06-30 08:01 UTC
