### ISSUE TITLE
[Camel] Adding a new component requires a refresh in project explorer

### ISSUE THREAD

**Issue by apupier** [fabric8io/fabric8-forge#360] opened 2016-07-05 08:45 UTC
- in JBDS, install Forge Camel addon
- create a Fuse Camel project with Java DSL(you can install Fuse Tooling for that)
- Open the java file corresponding to the Camel Route
- Ctrl+4
- Choose:  "Camel: new Component"
- Fill the wizard and click finish

--> Need to refresh the project to see the new *ComponentFactory.java file
--> nothing else has been created, is it normal?

**Comment by davsclaus** [comment] 2016-07-05 08:54
What version of the camel addon and jboss forge are you using?

**Comment by apupier** [comment] 2016-07-05 09:25
2.0.100 for JBoss Forge UI plugin
2-2-210 for Camel addon
3.3.2.Final for the Forge

**Comment by davsclaus** [comment] 2016-07-05 09:30
JBoss Forge in IDEA/Eclipse etc do a "save all" or some kind of refresh command after it has been executed. We had this kind of issue a while back in IDEA and it fixed that problem there. 

Not sure why Eclipse may have a problem still. Maybe it has a "flaky" new file detection or something. But the Forge guys such as @gastaldi can maybe find out if something is needed in their forge-eclipse module.

**Comment by gastaldi** [comment] 2016-07-05 14:57
Interesting. I'll try to reproduce this in JBT

**Comment by gastaldi** [comment] 2016-07-05 19:03
I managed to reproduce it. Will fix that asap

**Comment by gastaldi** [comment] 2016-07-05 19:27
Fixed! Thanks for reporting that! Created https://issues.jboss.org/browse/JBIDE-22690 to track that in JBoss Tools

**Comment by davsclaus** [comment] 2016-07-06 06:31
Thanks @gastaldi will this be in the next jboss forge release (eg after 3.2.2 ?)

**Comment by gastaldi** [comment] 2016-07-06 09:58
This is going be available in JBoss Tools 4.4.1.M2. It was not a bug in Forge, but the Eclipse plugin.

**Comment by davsclaus** [comment] 2016-07-07 11:27
Thanks as this is being fixed in JBoss Tools we are closing this ticket.

**Closed as completed by davsclaus** 2016-07-07 11:27 UTC
